on:
  push:
    branches:
    - hotcode
    - develop

name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test download small file
      run: go run ./cmd/gdown/ "https://drive.google.com/uc?id=0B9P1L--7Wd2vU3VUVlFnbTgtS2c"